services:
  postgres:
    container_name: postgres-sql-library
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: library_docker
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks: 
      - spring-demo
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev-library
    image: maildev/maildev
    ports: 
      - "1080:1080"
      - "1025:1025"
    networks: 
      - spring-demo

networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local
